### ISSUE TITLE
Enum Visitors having the same nice lambda builders as Unions

### ISSUE THREAD

**Issue by felixdesouza** [palantir/conjure-java#1058]
## What happened?
Expected to be able to use the lambda form of the visitor when looking at an enum, but turns out it's not generated.

## What did you want to happen?
Have the same lambda form available to us, the same way it is for union types.

**Comment by carterkozak** [comment]
This sounds reasonable to me, would you be interested in contributing the fix?

**Comment by felixdesouza** [comment]
Yeah, will give it a go if I a have a few cycles.

**Comment by diogoholanda** [comment]
@felixdesouza did you ever get to it? =]
I thought this was already a thing, but was unable to find the method, so I guess not.

The Visitor pattern is much safer than the switch-case pattern, but without those method it is quite verbose to manually create a visitor for an enum. Unfortunately, I don't think I'll have cycles to implement it in the short term, so this is just adding support for the feature =]

**Comment by felixdesouza** [comment]
I got most of the way through, and was trying to set up tests, and then I switched teams aha. I might have a look again in the coming weeks.
