### ISSUE TITLE
Provide ability to access dynamic query parameters

### ISSUE THREAD

**Issue by skedida** [palantir/conjure-java#1270]
## What happened?

We have a use case where we need to access query parameters in an HTTP request, and these query parameters are not known at compile time but are part of the runtime state of the server. For instance, a client may send us a query parameter that says `myQueryParameter.myOtherDynamicField=100`. For us, `myQueryParameter` is known at compile time but `myOtherDynamicField` is _not_ known at compile time and is based on some other state that only exists at runtime. There is currently no easy way to access such query parameters.

## What did you want to happen?
- One idea would be to provide a "context" object in the generated Java clients that provides access to all query parameters.
- Another idea specific to our use case is to provide access to query parameters that start with some string (e.g. `myQueryParameter.`). Perhaps in the conjure definition `myQueryParameter` can be declared as potentially having dynamic subfields and then in the generated conjure classes we can just get all query parameters that are "children" of `myQueryParemeter`

**Comment by tdeitch** [comment]
This should be fixed by the `RequestContext` object added in #1273, please re-open if not.
