### ISSUE TITLE
Generated enum valueOf method is incorrectly case-insensitive

### ISSUE THREAD

**Issue by sfackler** [palantir/conjure-java#134]
The valueOf method generated for enums (which is also used for deserialization) upper-cases input, in violation of the conjure spec.

https://github.com/palantir/conjure-java/blob/develop/conjure-java-core/src/integrationInput/java/com/palantir/product/EnumExample.java#L60-L71

**Comment by sfackler** [comment]
https://github.com/palantir/conjure/issues/184

**Comment by markelliot** [comment]
I think the case-insensitivity here is reasonably desirable and likely hard to remove without a major break (and I'm not sure it's worth a major break).

**Comment by sfackler** [comment]
Should this be a spec update instead then?

I don't really see where this behavior is providing all that much value - nothing else in the code we generate is case insensitive (field names etc).

**Comment by markelliot** [comment]
I'd prefer a spec update -- we added this leniency at the request of early adopters.

More broadly, we might want to consider allowing unions to contain 'null' object values and dropping enums, as they're a subset of the functionality of unions.

**Comment by carterkozak** [comment]
Could you expand upon the rationale for supporting mixed case strings? Are we certain the concerns raised by early adopters are still relevant? I'd appreciate if you could link me to that discussion.

**Comment by iamdanfox** [comment]
Discussion moved to https://github.com/palantir/conjure/issues/193
