### ISSUE TITLE
Consideration: generate code for built-in types?

### ISSUE THREAD

**Issue by nmiyake** [palantir/conjure-java#137]
Currently, generated Java code hard-codes imports for types like `SafeLong`, `ResourceIdentifier`, etc. For example:

```
package com.palantir.product;

import com.palantir.conjure.java.lib.SafeLong;
import com.palantir.ri.ResourceIdentifier;
import com.palantir.tokens.auth.AuthHeader;
import com.palantir.tokens.auth.BearerToken;
....

    @GET
    @Path("base/string")
    String string(@HeaderParam("Authorization") @NotNull AuthHeader authHeader);
```

This could cause issues because the resolution of these imports is dependent on the project setup.

That is, 2 projects that use the exact same Conjure definition and Conjure generator of the same version can generate incompatible code depending on the version of `ResourceIdentifier` that is resolved within their project.

The only way to truly avoid this is to always generate the built-in types as part of the Conjure generation process (and clients would need to write code to convert between the generated built-in types and the "real" types like `com.palantir.tokens.auth.BearerToken`).

An intermediate solution would be to define all of these types in the `conjure.java` project (as is done with `SafeLong`) and make it a requirement that, if code is generated using a given version of Conjure, then that version of `conjure.java.lib` must be imported in the project.

As it stands right now, the true compatibility graph is spread out among multiple repos -- you have to track the compatibility between versions of `com.palantir.ri` and Conjure, `com.palantir.tokens` and Conjure, etc. This isn't an issue right now because there are no breaking changes, but if there ever were to be then this would be extremely hard to reason through.

This came up in a discussion between @bmoylan and I when we were discussing analogous issues in Go.

**Comment by nmiyake** [comment]
Right now this is more of a future/theoretical concern so don't expect much to be done about it, but curious to hear what people think from a conceptual/theoretical perspective -- @iamdanfox and @uschi2000 for feedback when you get a chance (not urgent)

**Comment by uschi2000** [comment]
I think the right solution here is to properly version the packages in question, i.e., introduce `com.palantir.tokens2.foobar` etc when necessary. At least for Palantir-internal code, requiring users to translate between privately-generated BearerToken and **the** BearerToken would be extremely cumbersome.

**Comment by nmiyake** [comment]
Yup I think that sounds reasonable -- if there are guaranteed not to be any breaks within a given version path, then the per-project resolution does not matter since the import path establishes the contract. I think that's a sufficient way to address the underlying issue, so will close this out. Thanks for the feedback!
