### ISSUE TITLE
Make primitive fields required on builder.build()?

### ISSUE THREAD

**Issue by dxiao** [palantir/conjure-java#14]
For non-primitive, non-optional, non-collection type fields, we require that the user explicitly set the field on the builder, or else throw an exception. I get that logic, cause not saying optional implies required, means they should be set. However, we do not do the same check for primitive fields. That is to say, the following type definition:

    Foo:
      fields:
        bar: integer

will allow the following builder invocation to build, successfully:

    Foo.builder().build();

this seems inconsistent with the idea that the server controls default parameters. Can we make primitive fields required to be called as well?

One implementation for this can be found in internal gerrit #306681 , can port to here if it's reasonable.

**Comment by mnazbro** [comment]
The main reason for not changing this in the past was legacy reasons. The benefit of being explicit here seems to be important enough to change backwards compatibility.

**Comment by iamdanfox** [comment]
I agree that this needs to get fixed. Proposing adding some extra state for all primitive fields in a builder:

```diff
 @Generated("com.palantir.conjure.java.types.BeanBuilderGenerator")
 @JsonIgnoreProperties(ignoreUnknown = true)
 public static final class Builder {
     private boolean coin;
+    private boolean _coinInitialized = false;
 
     private Builder() {}
 
     public Builder from(BooleanExample other) {
         coin(other.getCoin());
         return this;
     }
 
     @JsonSetter("coin")
     public Builder coin(boolean coin) {
         this.coin = coin;
+        this._coinInitialized = true;
         return this;
     }
 
+     private static void validateFields(boolean coinInitialized) {
+         List<String> missingFields = null;
+         missingFields = addFieldIfMissing(missingFields, coinInitialized, "coin");
+         if (missingFields != null) {
+             throw new IllegalArgumentException(
+                     "Some required fields have not been set: " + missingFields);
+         }
+     }
+ 
+     private static List<String> addFieldIfMissing(
+             List<String> prev, boolean fieldValue, String fieldName) {
+         List<String> missingFields = prev;
+         if (!fieldValue) {
+             if (missingFields == null) {
+                 missingFields = new ArrayList<>(1);
+             }
+             missingFields.add(fieldName);
+         }
+         return missingFields;
+     }
+
     public BooleanExample build() {
+        validateFields(_coinInitialized);
         return new BooleanExample(coin);
     }
 }
```

This `validateFields` and `addFieldIfMissing` match the existing code we generate to validate non-primitives.

**Comment by markelliot** [comment]
Originally, the primary objects were used by Jackson during deserialization (despite the private constructor), given the changes that have happened, this proposal for moving some validation of fields ought to move all field validation to the builder, and could also move assumptions about the immutability of sets/lists and so forth, most likely.

**Comment by iamdanfox** [comment]
@markelliot do you mind if I just pop this initial implementation up first so that we can get our conjure-verification tests passing, then we can unify the two validateFields functions in a later pure-refactor PR?
