### ISSUE TITLE
Generated conjure types should mark the parameter to equals methods @Nullable

### ISSUE THREAD

**Issue by mharris-mharris** [palantir/conjure-java#1911]
## What happened?

Currently attempting to apply the NullAway plugin, and getting errors about passing a nullable value into the equals method of a conjure generated enum.  This fails because the field is not marked @Nullable, even though this is a reasonable thing to do.

## What did you want to happen?

Should be @Nullable and the NullAway plugin should respect this.

**Comment by carterkozak** [comment]
@amrasarfeiniel Are you using the latest conjure release?

**Comment by mharris-mharris** [comment]
com.palantir.conjure.java:* = 6.66.0
looks like the latest release of conjure java

**Comment by carterkozak** [comment]
And that version was used to _generate_ the classes in question?

**Comment by carterkozak** [comment]
Closing due to:
https://github.com/palantir/conjure-java/releases/tag/6.63.0
https://github.com/palantir/conjure-java/releases/tag/6.65.0
