### ISSUE TITLE
Error classes do not have private constructors

### ISSUE THREAD

**Issue by mnazbro** [palantir/conjure-java#193]
## What happened?

Generated objects do not enforce non-instantiability through a private constructor even though the classes are final and all of the functions on the class are static.

## What did you want to happen?

There is also a private constructor in those objects.

**Comment by iamdanfox** [comment]
@mnazbro I think conjure-java's generated objects and error classes already have private constructors. Can you paste a snippet of the generated code that looked bad? (Also what version of conjure-java are you using?

- error class: [ConjureErrors](https://github.com/palantir/conjure-java/blob/2.8.0/conjure-java-core/src/integrationInput/java/com/palantir/another/ConjureErrors.java#L13) (already private)
- regular object class: [ManyFieldExample](https://github.com/palantir/conjure-java/blob/2.8.0/conjure-java-core/src/integrationInput/java/com/palantir/product/ManyFieldExample.java#L43)

**Comment by mnazbro** [comment]
Interesting, maybe I was on an older version of Conjure earlier as it looks like the private constructor is there now.
