### ISSUE TITLE
Infinities are incorrectly serialized

### ISSUE THREAD

**Issue by sfackler** [palantir/conjure-java#31]
The spec indicates they should serialize as `"NaN"`, but they actually serialize as `"Infinity"` and `"-Infinity"`.

**Comment by iamdanfox** [comment]
Closing out as the spec was amended here https://github.com/palantir/conjure/blob/develop/docs/rfc/005-handling-double-nan-and-infinity.md and conjure-java runs against the conjure-verification test-cases 0.6.0 which includes cases for "NaN", "Infinity" and "-Infinity"

https://github.com/palantir/conjure-verification/blob/0.6.0/test-cases.yml#L59-L61
