### ISSUE TITLE
Consider Staged Builders

### ISSUE THREAD

**Issue by carterkozak** [palantir/conjure-java#355]
## What happened?

If we neglect to set all required fields in a bean builder, currently it results in failure at runtime.

## What did you want to happen?

We can use staged builders to cause compilation failures in cases that currently only fail at runtime.
Downside of this approach is that existing builders would have to be re-ordered, so it would have to exist behind a feature flag.

**Comment by markelliot** [comment]
I think a more flexible check than staged builders would be something using errorprone, which could also provide for warnings on optionals.

________________________________

**Comment by carterkozak** [comment]
Errorprone has the potential to be more flexible, but the check itself would be complicated. It could allow us to avoid changing any existing correct code, but the downsides are higher compile-time computational cost for larger projects, lack of integration with other tools (IDE), and requiring error-prone integration. Given the option, I would prefer to leverage the compiler as much as possible for problems that the compiler is good at (type checking), and rely on errorprone for things that the compiler cannot do.

Perhaps the cost of changing generated code is too high at this point (it would certainly be painful for the large project I primarily work on) and the benefits of additional safety aren't worth this sort of change, in which case I agree that errorprone is a reasonable compromise.

**Comment by markelliot** [comment]
Right, I think the cost of change here would be very high and for some usages perhaps not possible (consider cases where today a builder is passed as an argument).

An errorprone check may or may not be possible for complex usage, but for straight-forward builder calls should provide a low cost compile-time signal of issues.

________________________________

**Comment by raiju** [comment]
Can be enabled using the `useStagedBuilders` flag
