### ISSUE TITLE
Generated java for optional<set<...>> types can fail to compile 

### ISSUE THREAD

**Issue by xfalco** [palantir/conjure-java#536]
Suppose a conjure object containing a field that is an optional set type: 

```
OptionalFoo:
        fields:
          item: optional<set<StringAliasExample>>
```
The generated objects java will contain a builder entry accepting an `Optional<? extends Set<StringAliasExample>>` type:

```
@JsonSetter(value = "otherItem", nulls = Nulls.SKIP)
        public Builder item(Optional<? extends Set<StringAliasExample>> item) {
            this.item =
                    (Optional<Set<StringAliasExample>>)
                            Preconditions.checkNotNull(item, "item cannot be null");
            return this;
        }
```

However, this will fail to compile on at least some java versions (ex: openjdk 11.0.2), because the `Optional<? extends Set<StringAliasExample>>` covariant type returned by the Preconditions check is not compatible with the invariant inner variable type (`Optional<Set<StringAliasExample>>`) it is being typecasted to. Example compilation error:

```
Preconditions.checkNotNull(item, "item cannot be null");
                                                      ^
  required: Optional<Set<StringAliasExample>>
  found:    Optional<CAP#1>
  where CAP#1 is a fresh type-variable:
    CAP#1 extends Set<StringAliasExample> from capture of ? extends Set<StringAliasExample>
```

verified on conjure-java 4.0.0

**Comment by JacekLach** [comment]
Guess that's an edge case I missed in https://github.com/palantir/conjure-java/pull/9#discussion_r192091160
