### ISSUE TITLE
RetrofitListenableFutures return a null ResponseBody on 503

### ISSUE THREAD

**Issue by dtobin** [palantir/conjure-java#705]
## What happened?

We have a conjure-defined endpoint with `returns: binary`. When `retrofitListenableFutures = true` is enabled, the return type for the endpoint in the retrofit interface is `ListenableFuture<ResponseBody>`. Occasionally in testing the endpoint produces a `ListenableFuture` which returns a null ResponseBody from `ListenableFuture.get()`, which then causes an NPE.

This issue prevents us from upgrading conjure-java because it appears that RetrofitListenableFutures is the only option in conjure-java versions 5.0.0+ https://github.com/palantir/conjure-java/pull/641

Reproduced on conjure-java versions 4.8.1 and 5.0.0.

## What did you want to happen?

Binary endpoints with `RetrofitListenableFutures` should never return a null `ResponseBody`; either an exception should be thrown or a valid response body should be returned.

**Comment by dtobin** [comment]
Update: this appears to be caused when a server returns a 503 on an endpoint that returns a binary response body.

**Comment by ferozco** [comment]
Should be addressed by https://github.com/palantir/conjure-java-runtime/pull/1479
