### ISSUE TITLE
Generated Java code should not import java.lang classes

### ISSUE THREAD

**Issue by dtobin** [palantir/conjure-java#89]
Generated service definitions currently include imports for `java.lang` classes like `Object`, `String`, `Deprecated`, and `Void`. The `java.lang` package is imported implicitly, so code formatters like https://github.com/diffplug/spotless/ will reject these imports. For now people can workaround this by configuring their formatter to skip the generated files, but it would be a better experience if the generated services have the correct imports to begin with.

This bug does not appear to happen in generated types, only in generated services.

**Comment by iamdanfox** [comment]
As a stop-gap solution, we've made baseline stop trying to format any files with `/generated` in the path, so baseline 0.37.3 should get rid of this symptom: https://github.com/palantir/gradle-baseline/releases/tag/0.37.3

In sync that this is worth solving properly though!

**Comment by carterkozak** [comment]
I think this is fixed

**Comment by carterkozak** [comment]
This is fixed, we no longer import `java.lang` types.
