### ISSUE TITLE
FR: Defaulting visitors in java

### ISSUE THREAD

**Issue by mcintyret** [palantir/conjure-java#98]
## Motivation
For a union type of A, B, C, D, it isn't unusual do want to do `if (value is A) do X else do Y`.

It would be nice if conjure supported this OOTB.

Note that this is already possible with typescript.

## Proposal

instead of generating visitors as such:

```
interface Visitor<T> {
    T visitA(A a);
    T visitB(B b);
    T visitC(C c);
    T visitUnknown(String type);
}
```

I propose

```
interface Visitor<T> {
    default T visitA(A a) {
        return visitDefault();
    }

    default T visitB(B b) {
        return visitDefault();
    }

    default T visitC(C c) {
        return visitDefault();
    }

    default T visitUnknown(String type) {
        return visitDefault();
    }

    T visitDefault();
}
```
A downside of the proposal is that users are then forced to implement `visitDefault()` even when they don't need it (when they have an implementation for each type in the union). One solution would be to have that have a default implementation too (`throw new UnsupportedOperationException()`?) although that feels like it would lead to runtime breaks. A better solution might be to make the above a separate `DefaultingVisitor<T> extends Visitor<T>` interface, so users only have to implement `visitDefault()` when they need to.

**Comment by uschi2000** [comment]
The rationale of today's visitor design is that the implementor is forced to handle all cases explicitly. This becomes important when a new field is added: my code would to compile unless I handle the new thing everywhere. Even though this may be annoying in some cases (as you note), I believe it is overall the more desirable behavior.

// from mobile

**Comment by carterkozak** [comment]
Agree with @uschi2000, It's a feature that adding new types causes compilation breaks. I want to be sure that all visitors properly handle my new type.

The case `if (value is A) do X else do Y` would be better served by optional-getters (e.g. `Optional<A> getIfA()`) on the union type, though my intuition is that would be misused in places where visitors are a better fit.

**Comment by iamdanfox** [comment]
I'd like to close this out as I think the visitors in their current state are an intentional design decision. Yes they're a bit clunky in Java, but I think encouraging devs to handle cases exhaustively is preferable to slightly risky brevity.

At the end of the day, you can always build functions that just return booleans:

```java
public static boolean isVariantA(MyUnion union) {
    return union.accept(new Visitor<Boolean>() {
     //...
    });
}
```
